var procs = 
    [ 'allocate_shardkey'
    , 'add_facebook_creds'
    , 'add_source_industry'
    , 'add_source_page'
    , 'block_facebook_creds'
    , 'crawler_notify'
    , 'db_time'
    , 'ebay_add_or_update'
    , 'get_accessory_patterns'
    , 'get_brands'
    , 'get_commercial_patterns'
    , 'get_corpus_texts'
    , 'get_ebay_short_list'
    , 'get_facebook_creds'
    , 'get_industry_corpus'
    , 'get_industry_table'
    , 'get_industries'
    , 'get_models'
    , 'get_my_ip'
    , 'get_series'
    , 'get_source_table'
    , 'get_source_industry_qa'
    , 'get_source_industry_qa_all'
    , 'get_source_industry_table'
    , 'get_source_vertical_table'
    , 'get_vertical_table'
    , 'get_tags_table'
    , 'log_crawler'
    , 'monitor_list'
    , 'monitor_remove'
    , 'monitor_set'
    ];

exports.procs = procs;